# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  role:
    description: |
      role config option exists to deploy the charmed-mongodb application as a shard, 
      config-server, or as a replica set.
    type: string
    default: replication
  ldap-user-to-dn-mapping:
    default: ''
    type: string
    description: |
      A quote-enclosed JSON-string representing an ordered array of documents. Each document contains a regular expression match and either a substitution or ldapQuery template used for transforming the incoming username. Since the list is ordered, this order can be used to provide fine-grained tuning for building the right DN or the right ldapQuery for the user.
      example: '[{
        match : "([^@]+)@([^@\\.]+)\\.example\\.com",
        substitution: "CN={0},CN=Users,DC={1},DC=example,DC=com"
      }]'
  ldap-query-template:
    default: ''
    type: string
    description: |
      A RFC4516 formatted LDAP query URL template, which is used for authorization.
      It must contain either `{USER}` representing the authenticated user, or `{PROVIDED_USER}` representing the supplied username (before authentication or LDAP transformation).
      `{PROVIDED_USER}` should be used only if no value in the `ldap-user-to-do-mapping` config option is provided.
      If this configuration is not provided, a default string will be computed based on the base_dn returned by the GLAuth k8s charm.
      example: “dc=example,dc=com??sub?(&(objectClass=groupOfNames)(member={USER}))"
  system-users:
    type: secret
    description: |
      Configure the internal system users and their passwords. The passwords will
      be auto-generated if this option is not set. It is for internal use only
      and SHOULD NOT be used by applications. This must be a Juju Secret URI pointing
      to a secret that contains a map with the following content: `<username>: <password>`.
      Possible users: `backup`, `logrorate`, `monitor`, `operator`.
      This option is only compatible with `replication` and `config-server` roles.
  pause-after-unit-refresh:
    description: |
      Wait for manual confirmation to resume refresh after these units refresh

      Allowed values: "all", "first", "none"
    type: string
    default: first
