#!/bin/sh -e
# Copyright 2022 Canonical Ltd
# See LICENSE file for licensing details.

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH="lib:src"
else
    export PYTHONPATH="lib:src:$PYTHONPATH"
fi

poetry export -f requirements.txt -o requirements.txt
poetry run flake8
poetry run coverage run --branch --source=src -m pytest -v "$@"
poetry run coverage report -m
