{
 "title": "MongoDB ReplSet Summary",
 "tags": [
  "MongoDB_HA",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "query": "loki" },
   { "name": "prometheusds", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_application=\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(mongodb_up,cluster)"
    }
   },
   {
    "name": "replset",
    "label": "Replica Set",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\"}, set)"
    }
   },
   {
    "name": "node_name",
    "label": "Node Name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{service_name=~\"$service_name\"}, node_name)"
    }
   },
   {
    "name": "service_name",
    "label": "Service Name",
    "query": {
     "query": "label_values(mongodb_mongod_replset_my_state{cluster=~\"$cluster\",set=\"$replset\"}, service_name)"
    }
   },
   {
    "name": "environment",
    "label": "Environment",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, environment)"
    }
   },
   {
    "name": "replication_set",
    "label": "Replication Set",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, replication_set)"
    }
   },
   {
    "name": "database",
    "label": "Database",
    "query": {
     "query": "label_values(pg_stat_database_tup_fetched{service_name=~\"$service_name\",datname!~\"template.*|postgres\"},datname)"
    }
   },
   {
    "name": "node_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, node_type)"
    }
   },
   {
    "name": "service_type",
    "label": "Type",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, service_type)"
    }
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": {
     "query": "label_values({__name__=~\"pg_up|mysql_up|mongodb_up|proxysql_mysql_status_active_transactions\"}, schema)"
    }
   },
   {
    "name": "username",
    "label": "Username",
    "query": {
     "query": "label_values(mysql_info_schema_user_statistics_connected_time_seconds_total{service_name=\"$service_name\"},user)"
    }
   },
   {
    "name": "secondary",
    "label": "Secondary",
    "query": {
     "query": "query_result(mongodb_mongod_replset_my_state{cluster=~\"$cluster\",set=\"$replset\"}==2)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "ReplSet Members",
   "type": "stat",
   "description": "This shows how many members are configured in the replica set.",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_mongod_replset_number_of_members{juju_application=~\"$juju_application\",juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_unit=~\"$juju_unit\"} "
    }
   ]
  },
  {
   "title": "ReplSet Last Election",
   "type": "stat",
   "description": "This shows the time since the last election.",
   "gridPos": { "h": 7, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(mongodb_mongod_replset_member_election_date{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "MongoDB Versions",
   "type": "table",
   "gridPos": { "h": 11, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "avg by(service_name, engine) (mongodb_mongod_storage_engine{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})"
    },
    {
     "expr": "avg by(service_name, mongodb) (mongodb_version_info{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Operations - $service_name",
   "type": "graph",
   "description": "Operations are classified by legacy wire protocol type (insert, update, and delete only).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 13 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name, type) (rate(mongodb_op_counters_repl_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_op_counters_repl_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "repl - "
    },
    {
     "expr": "avg by(service_name, type) (rate(mongodb_mongod_op_counters_repl_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_op_counters_repl_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "repl - "
    },
    {
     "expr": "avg by(service_name, type) (rate(mongodb_op_counters_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_op_counters_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Max Heartbeat Time / Elections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Max Heartbeat Time",
   "type": "graph",
   "description": "Time span between now and last heartbeat from replicaset members.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - avg by(service_name) (max by(name) (mongodb_mongod_replset_member_last_heartbeat{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})) * on(name) group_right() avg by(service_name) (mongodb_mongod_replset_my_name{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Elections",
   "type": "graph",
   "description": "Count of elections. Usually zero; 1 count by each healthy node will appear in each election. Happens when the primary role changes due to either normal maintenance or trouble events.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by(service_name) (changes(mongodb_mongod_replset_member_election_date{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Oplog Recovery Window",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Recovery Window - $service_name",
   "type": "graph",
   "description": "Timespan 'window' between newest and the oldest op in the Oplog collection.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "time() - avg by(service_name) (mongodb_mongod_replset_oplog_tail_timestamp{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Now to End"
    },
    {
     "expr": "avg by(service_name) (mongodb_mongod_replset_oplog_head_timestamp{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"} - mongodb_mongod_replset_oplog_tail_timestamp{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Oplog Range"
    }
   ]
  },
  {
   "title": "Oplog Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Oplog Buffered Operations",
   "type": "graph",
   "description": "Repl buffer ops applied per sec.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name) (mongodb_mongod_metrics_repl_buffer_count{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})"
    }
   ]
  },
  {
   "title": "Oplog Getmore Time",
   "type": "graph",
   "description": "Time spent per second waiting for or fetching oplog docs in replication.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_network_getmores_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Oplog Processing Time - $service_name",
   "type": "graph",
   "description": "Times spent per second A) pre-loading oplog ops into parallel-executable batches B) Times spent pre-loading index values and C) repl batch apply phase.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_batches_total_milliseconds{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "Oplog Buffer Capacity - $service_name",
   "type": "graph",
   "description": "Current hard-coded max and actual size of repl batch buffer.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name) (mongodb_mongod_metrics_repl_buffer_size_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Used"
    },
    {
     "expr": "avg by(service_name) (mongodb_mongod_metrics_repl_buffer_max_size_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Oplog Operations - $service_name",
   "type": "graph",
   "description": "Count of A) getmores executed B) index values pre-loaded C) oplog docs applied per second against oplog collection in replication.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_preload_docs_num_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_docs_num_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Document Preload"
    },
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_preload_indexes_num_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_preload_indexes_num_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Index Preload"
    },
    {
     "expr": "avg by(service_name) (rate(mongodb_mongod_metrics_repl_apply_ops_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_repl_apply_ops_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))",
     "legendFormat": "Batch Apply"
    }
   ]
  },
  {
   "title": "MongoDB Services Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Latency Detail - $service_name",
   "type": "graph",
   "description": "Average latency of operations (classified by read, write, or (other) command).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 73 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name, type) (rate(mongodb_mongod_op_latencies_latency_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) / (rate(mongodb_mongod_op_latencies_ops_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) > 0) or irate(mongodb_mongod_op_latencies_latency_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]) / (irate(mongodb_mongod_op_latencies_ops_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]) > 0))"
    }
   ]
  },
  {
   "title": "Document Operations - $service_name",
   "type": "graph",
   "description": "Docs per second inserted, updated, deleted or returned. (N.b. not 1-to-1 with operation counts.)",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 81 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "avg by(service_name, state) (rate(mongodb_mongod_metrics_document_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_mongod_metrics_document_total{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m]))"
    }
   ]
  },
  {
   "title": "Cache - $service_name",
   "type": "graph",
   "description": "MongoDB keeps most recently used data in RAM. If you have created indexes for your queries and your working data set fits in RAM, MongoDB serves all queries from memory.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 89 },
   "repeat": "service_name",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mongodb_tcmalloc_cache_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[$interval]) or irate(mongodb_tcmalloc_cache_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"}[5m])",
     "legendFormat": " - "
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_tcmalloc_tcmalloc_thread_cache_free_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Free Thread Cache"
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_tcmalloc_tcmalloc_central_cache_free_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Free Central Cache"
    },
    {
     "expr": "avg by(service_name) (mongodb_ss_tcmalloc_tcmalloc_transfer_cache_free_bytes{juju_application=\"$juju_application\",juju_model=\"$juju_model\",juju_model_uuid=\"$juju_model_uuid\",juju_unit=\"$juju_unit\",service_name=~\"$service_name\"})",
     "legendFormat": "Free Transfer Cache"
    }
   ]
  }
 ]
}