name: Tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tox
        run: python3 -m pip install tox
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Run linters
        run: tox -e lint
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install tox
        run: python3 -m pip install tox
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Run tests
        run: tox -e unit
  integration-test-microk8s:
    name: Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          channel: 1.23/stable
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install tox
        run: python3 -m pip install tox
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Run integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: sg microk8s -c "tox -e integration -- --model testing"
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          # TEMPLATE-TODO: Replace the application name
          app: operator-template
          model: testing

  tls-integration-test-microk8s:
    name: TLS Integration tests (microk8s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup operator environment
        uses: charmed-kubernetes/actions-operator@main
        with:
          provider: microk8s
          # This is needed until https://bugs.launchpad.net/juju/+bug/1977582 is fixed
          channel: 1.23/stable
          bootstrap-options: "--agent-version 2.9.29"
      - name: Install tox
        run: python3 -m pip install tox
      - name: Install poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      - name: Run tls integration tests
        # set a predictable model name so it can be consumed by charm-logdump-action
        run: sg microk8s -c "tox -e tls-integration -- --model testing"
      - name: Dump logs
        uses: canonical/charm-logdump-action@main
        if: failure()
        with:
          # TEMPLATE-TODO: Replace the application name
          app: operator-template
          model: testing
