# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v41.1.1

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.6.2
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}

  terraform-rs-test:
    name: Terraform - Validation of replica-set product module
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (GitHub hosted) Free up disk space
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable

      - name: (self hosted) Disk usage
        run: df --human-readable

      - name: Install terraform snap
        run: |
          sudo snap install terraform --channel=latest/stable --classic

      - name: Lint / format / validate TF modules
        run: |
          pushd ./terraform
          for dir in charm/replica_set product/replica_set; do
            (cd "${dir}" && terraform init && terraform fmt && terraform validate)
          done
          popd

      - name: run checks - prepare
        run: |
          sudo snap install juju --channel=3.6

      - name: microk8s setup
        run: |
          sudo snap install microk8s --channel=1.27-strict
          sudo usermod -a -G snap_microk8s "$(whoami)"
          mkdir -p ~/.kube
          sudo chown -R "$(whoami)" ~/.kube
          newgrp snap_microk8s
          sudo microk8s enable dns storage ingress

      - name: Juju setup
        run: |
          mkdir -p ~/.local/share/juju
          sudo --user "$USER" juju bootstrap 'microk8s' --config model-logs-size=10G
          juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
          juju add-model test

      - name: Terraform deploy - replica-set product module
        run: |
          MODEL=$(juju show-model test | grep "model-uuid" | awk '{split($0, a, ": "); print a[2]}')
          pushd ./terraform/product/replica_set/
          terraform apply \
            -var="mongodb_k8s={\"model_uuid\": \"$MODEL\"}" \
            -var="self_signed_certificates={\"model_uuid\": \"$MODEL\"}" \
            -var="s3_integrator={\"model_uuid\": \"$MODEL\", \"config\": {\"bucket\": \"test\"}}" \
            -var="data_integrator={\"model_uuid\": \"$MODEL\"}" \
            -auto-approve
          popd

      - name: Wait for juju deployment
        run: |
          # TODO - remove this when juju wait-for starts reporting the up to date status
          until timeout 2m juju wait-for model test --query='life=="alive" && status=="available"'
          do
            echo "Retrying in 5 seconds..."
            juju status -m test
            sleep 5
          done

  terraform-sharding-test:
    name: Terraform - Validation of sharded cluster product module
    continue-on-error: true
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (GitHub hosted) Free up disk space
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable

      - name: (self hosted) Disk usage
        run: df --human-readable

      - name: Install terraform snap
        run: |
          sudo snap install terraform --channel=latest/stable --classic

      - name: Lint / format / validate TF modules
        run: |
          pushd ./terraform
          for dir in charm/replica_set charm/sharded product/replica_set product/sharded; do
            (cd "${dir}" && terraform init && terraform fmt && terraform validate)
          done
          popd

      - name: run checks - prepare
        run: |
          sudo snap install juju --channel=3.6

      - name: microk8s setup
        run: |
          sudo snap install microk8s --channel=1.27-strict
          sudo usermod -a -G snap_microk8s "$(whoami)"
          mkdir -p ~/.kube
          sudo chown -R "$(whoami)" ~/.kube
          newgrp snap_microk8s
          sudo microk8s enable dns storage ingress

      - name: Juju setup
        run: |
          mkdir -p ~/.local/share/juju
          sudo --user "$USER" juju bootstrap 'microk8s' --config model-logs-size=10G
          juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
          juju add-model test

      - name: Terraform deploy - sharded cluster product module
        run: |
          MODEL=$(juju show-model test | grep "model-uuid" | awk '{split($0, a, ": "); print a[2]}')
          pushd ./terraform/product/sharded/
          terraform apply \
            -var="config_server={\"model_uuid\": \"$MODEL\"}" \
            -var="shards=[{\"app_name\": \"shard-one\", \"model_uuid\": \"$MODEL\"},{\"app_name\": \"shard-two\", \"model_uuid\": \"$MODEL\"}]" \
            -var="mongos_k8s={\"model_uuid\": \"$MODEL\"}" \
            -var="config_server={\"model_uuid\": \"$MODEL\"}" \
            -var="self_signed_certificates={\"model_uuid\": \"$MODEL\"}" \
            -var="s3_integrator={\"model_uuid\": \"$MODEL\", \"config\": {\"bucket\": \"test\"}}" \
            -var="data_integrator={\"model_uuid\": \"$MODEL\"}" \
            -auto-approve
          popd

      - name: Wait for juju deployment
        run: |
          # TODO - remove this when juju wait-for starts reporting the up to date status
          until timeout 2m juju wait-for model test --query='life=="alive" && status=="available"'
          do
            echo "Retrying in 5 seconds..."
            juju status -m test
            sleep 5
          done

  build:
    strategy:
      matrix:
        path:
          - .
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v41.1.1
    with:
      path-to-charm-directory: ${{ matrix.path }}
      cache: false

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@v41.1.1
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      cloud: microk8s
      microk8s-snap-channel: 1.29-strict/stable # renovate: latest microk8s
      juju-agent-version: 3.6.1 # renovate: juju-agent-pin-minor
      _beta_allure_report: true
    permissions:
      contents: write # Needed for Allure Report beta
