name: Charmed Operator Tests
on:
  workflow_call:
  pull_request:

jobs:
  lint:
    uses: ./.github/workflows/lint.yaml
  unit:
    uses: ./.github/workflows/unit.yaml
  integration:
    uses: ./.github/workflows/integration.yaml
