# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v24.0.6

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.6.2
        with:
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 25 # TODO: reduce to 5 minutes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit

  terraform-test:
    name: Terraform - Lint and Simple Deployment
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: lint charm module
        working-directory: ./terraform
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: lint test charm module
        working-directory: ./terraform/tests
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: run checks - prepare
        run: |
          sudo snap install juju --channel=3.6/beta --classic
          sudo snap install juju-wait --channel=latest/stable --classic
          sudo snap install jq
      - name: LXD setup
        run: |
          sudo snap refresh lxd --channel=latest/stable
          sudo adduser "$USER" 'lxd'
          # `newgrp` does not work in GitHub Actions; use `sg` instead
          sg 'lxd' -c "lxd waitready"
          sg 'lxd' -c "lxd init --auto"
          sg 'lxd' -c "lxc network set lxdbr0 ipv6.address none"
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
      - name: Juju setup
        run: |
          sg 'lxd' -c "juju bootstrap 'localhost' --config model-logs-size=10G"
          juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
          juju add-model test
      - name: Terraform deploy
        working-directory: ./terraform/tests/
        run: |
          terraform apply  -var "model_name=test" -target null_resource.simple_deployment_juju_wait_deployment -auto-approve

  build:
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v24.0.6
    strategy:
      matrix:
        path:
          - .
          - tests/integration/ha_tests/application_charm
          - tests/integration/relation_tests/application-charm
    with:
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        juju:
          # This runs on all runs
          - agent: 3.5.3 # renovate: juju-agent-pin-minor
            allure_report: true
          # This runs only on scheduled runs, DPW 21 specifics (scheduled + 3.6/X)
          - snap_channel: 3.6/stable
            allure_report: false
    name: Integration test charm | ${{ matrix.juju.agent || matrix.juju.snap_channel }}
    needs:
      - lint
      - unit-test
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@v24.0.6
    with:
      artifact-prefix: packed-charm-cache-false # TODO revert to "packed-charm-cache-true" when cache re-enabled
      cloud: microk8s
      microk8s-snap-channel: 1.29-strict/stable
      juju-agent-version: ${{ matrix.juju.agent }}
      juju-snap-channel: ${{ matrix.juju.snap_channel }}
      _beta_allure_report: ${{ matrix.juju.allure_report }}
    permissions:
      contents: write # Needed for Allure Report beta
    secrets:
      integration-test: |
        {  "AWS_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY }}",
          "AWS_SECRET_KEY": "${{ secrets.AWS_SECRET_KEY }}",
          "GCP_ACCESS_KEY": "${{ secrets.GCP_ACCESS_KEY }}",
          "GCP_SECRET_KEY": "${{ secrets.GCP_SECRET_KEY }}", }
