# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Tests

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

on:
  pull_request:
  schedule:
    - cron: "53 0 * * *" # Daily at 00:53 UTC
  # Triggered on push to branch "main" by .github/workflows/release.yaml
  workflow_call:
    outputs:
      artifact-prefix:
        description: build_charm.yaml `artifact-prefix` output
        value: ${{ jobs.build.outputs.artifact-prefix }}

jobs:
  lint:
    name: Lint
    uses: canonical/data-platform-workflows/.github/workflows/lint.yaml@v29.0.0

  lib-check:
    name: Check libraries
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          # Workaround for https://github.com/canonical/charmcraft/issues/1389#issuecomment-1880921728
          touch requirements.txt
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@2.6.2
        with:
          charmcraft-channel: latest/candidate # TODO: remove after charmcraft 3.3 stable release
          credentials: ${{ secrets.CHARMHUB_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          use-labels: false
          fail-build: ${{ github.event_name == 'pull_request' }}

  unit-test:
    name: Unit test charm
    runs-on: ubuntu-latest
    timeout-minutes: 25 # TODO: reduce to 5 minutes
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install tox & poetry
        run: |
          pipx install tox
          pipx install poetry
      - name: Run tests
        run: tox run -e unit

    terraform-lint:
    name: Terraform - Lint
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install terraform snap
        run: |
          sudo snap install terraform --channel=latest/stable --classic
      - name: lint charm module
        working-directory: ./terraform
        run: |
          terraform init
          terraform fmt
          terraform validate
      - name: lint test charm module
        working-directory: ./terraform/modules
        run: |
          terraform init
          terraform fmt
          terraform validate

  terraform-test:
    name: Terraform - Run terraform tests
    needs:
      - terraform-lint
    runs-on: ubuntu-22.04
    timeout-minutes: 120
    strategy:
      matrix:
        module:
          - name: replica set tests
            working_directory: terraform/modules/replica_set
            model_name: test-rs
          - name: sharded tests
            working_directory: terraform/modules/sharded_cluster
            model_name: test-sc
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install terraform snap
        run: |
          sudo snap install terraform --channel=latest/stable --classic
      - name: juju set up
        run: |
          sudo snap install juju --channel=3.6/beta --classic
          sudo snap install juju-wait --channel=latest/stable --classic
          sudo snap install jq
      - name: LXD setup
        run: |
          sudo snap refresh lxd --channel=latest/stable
          sudo adduser "$USER" 'lxd'
          # `newgrp` does not work in GitHub Actions; use `sg` instead
          sg 'lxd' -c "lxd waitready"
          sg 'lxd' -c "lxd init --auto"
          sg 'lxd' -c "lxc network set lxdbr0 ipv6.address none"
          sudo iptables -F FORWARD
          sudo iptables -P FORWARD ACCEPT
      - name: Juju setup
        run: |
          sg 'lxd' -c "juju bootstrap 'localhost' --config model-logs-size=10G"
          juju model-defaults logging-config='<root>=INFO; unit=DEBUG'
      - name: Terraform deploy ${{ matrix.module.name }}
        working-directory: ${{ matrix.module.working_directory }}
        run: |
          juju add-model ${{ matrix.module.model_name }}
          terraform init
          terraform apply  -var "model_name=${{ matrix.module.model_name }}" -target null_resource.juju_wait_deployment -auto-approve

  build:
    name: Build charm | ${{ matrix.path }}
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@v29.0.0
    strategy:
      matrix:
        path:
          - .
          - tests/integration/ha_tests/application_charm
          - tests/integration/relation_tests/application-charm
    with:
      charmcraft-snap-channel: latest/candidate # TODO: remove after charmcraft 3.3 stable release
      path-to-charm-directory: ${{ matrix.path }}

  integration-test:
    name: Integration test charm
    needs:
      - lint
      - unit-test
      - build
    uses: canonical/data-platform-workflows/.github/workflows/integration_test_charm.yaml@v29.0.0
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      cloud: microk8s
      microk8s-snap-channel: 1.29-strict/stable # renovate: latest microk8s
      juju-agent-version: 3.6.1 # renovate: juju-agent-pin-minor
      _beta_allure_report: true
    permissions:
      contents: write # Needed for Allure Report beta
    secrets:
      integration-test: |
        {  "AWS_ACCESS_KEY": "${{ secrets.AWS_ACCESS_KEY }}",
          "AWS_SECRET_KEY": "${{ secrets.AWS_SECRET_KEY }}",
          "GCP_ACCESS_KEY": "${{ secrets.GCP_ACCESS_KEY }}",
          "GCP_SECRET_KEY": "${{ secrets.GCP_SECRET_KEY }}", }
