on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: |
          Prefix for charm package GitHub artifact(s)

          Use canonical/data-platform-workflows build_charm.yaml to build the charm(s)
        required: true
        type: string

jobs:
  collect-integration-tests:
    name: Collect integration test spread jobs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions: {}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up environment
        run: |
          sudo snap install go --classic
          go install github.com/canonical/spread/cmd/spread@latest
          pipx install tox poetry
      - name: Collect spread jobs
        id: collect-jobs
        shell: python
        run: |
          import json
          import pathlib
          import os
          import subprocess

          spread_jobs = (
              subprocess.run(
                  [pathlib.Path.home() / "go/bin/spread", "-list", "github-ci"],
                  capture_output=True,
                  check=True,
                  text=True,
              )
              .stdout.strip()
              .split("\n")
          )
          jobs = []
          for job in spread_jobs:
              # Example `job`: "github-ci:ubuntu-24.04:tests/spread/test_charm.py:juju36"
              # no variant in mongodb for now
              # _, runner, task, variant = job.split(":")
              _, runner, task = job.split(":")
              # Example: "test_charm.py"
              task = task.removeprefix("tests/spread/")
              # For IS-hosted runners
              if "arm64" in runner:
                  architecture = "arm64"
              else:
                  architecture = "amd64"
              # Example: "test_charm.py:juju36 | amd64"
              name = f"{task} | {architecture}"
              # ":" character not valid in GitHub Actions artifact
              name_in_artifact = f"{task.replace('/', '-')}-{architecture}"
              jobs.append({
                  "spread_job": job,
                  "name": name,
                  "name_in_artifact": name_in_artifact,
                  "runner": runner,
              })
          output = f"jobs={json.dumps(jobs)}"
          print(output)
          with open(os.environ["GITHUB_OUTPUT"], "a") as file:
              file.write(output)
    outputs:
      jobs: ${{ steps.collect-jobs.outputs.jobs }}

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.collect-integration-tests.outputs.jobs) }}
    name: ${{ matrix.job.name }}
    needs:
      - collect-integration-tests
    runs-on: ${{ matrix.job.runner }}
    timeout-minutes: 217 # Sum of steps `timeout-minutes` + 5
    permissions: {}
    steps:
      - name: Disk usage
        timeout-minutes: 1
        run: df --human-readable
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Set up environment
        timeout-minutes: 5
        run: sudo snap install charmcraft --classic
      # TODO: remove when https://github.com/canonical/charmcraft/issues/2105 and
      # https://github.com/canonical/charmcraft/issues/2130 fixed
      - run: |
          sudo snap install go --classic
          go install github.com/canonical/spread/cmd/spread@latest
      - name: Download packed charm(s)
        timeout-minutes: 5
        uses: actions/download-artifact@v7
        with:
          pattern: ${{ inputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Run spread job
        timeout-minutes: 60
        id: spread
        # TODO: replace with `charmcraft test` when
        # https://github.com/canonical/charmcraft/issues/2105 and
        # https://github.com/canonical/charmcraft/issues/2130 fixed
        run: ~/go/bin/spread -vv -artifacts=artifacts "${VAR_SPREAD_JOB}"
        env:
          VAR_SPREAD_JOB: ${{ matrix.job.spread_job }}
      - timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: snap list
      - name: Select model
        timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        id: juju-switch
        run: |
          # sudo needed since spread runs scripts as root
          # "testing" is default model created by concierge
          sudo juju switch testing
          mkdir ~/logs/
      - name: juju status
        timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: sudo juju status --color --relations | tee ~/logs/juju-status.txt
      - name: juju debug-log
        timeout-minutes: 3
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: sudo juju debug-log --color --replay --no-tail | tee ~/logs/juju-debug-log.txt
      - name: jhack tail
        timeout-minutes: 3
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: sudo jhack tail --printer raw --replay --no-watch | tee ~/logs/jhack-tail.txt
      - name: Upload logs
        timeout-minutes: 5
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        uses: actions/upload-artifact@v7
        with:
          name: logs-integration-test-${{ matrix.job.name_in_artifact }}
          path: ~/logs/
          if-no-files-found: error
      - name: Disk usage
        timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: df --human-readable
