name: Release to 6/edge

on:
  push:
    branches:
      - 6/edge

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml
    permissions:
      actions: read
      contents: write # Needed for Allure Report beta

  release:
    name: Release charm
    needs:
      - ci-tests
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v49.0.0
    with:
      track: 6
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      actions: read
      contents: write # Needed to create git tags
