# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub edge

on:
  push:
    branches:
      - 8/edge

jobs:
  tag:
    name: Create charm refresh compatibility version git tag
    uses: canonical/data-platform-workflows/.github/workflows/tag_charm_edge.yaml@v42.1.0
    with:
      track: "8"
    permissions:
      contents: write # Needed to create git tag

  ci-tests:
    needs: tag
    uses: ./.github/workflows/ci.yaml
    secrets: inherit
    permissions:
      contents: write

  release:
    name: Release charm
    needs:
      - ci-tests
      - tag
    uses: canonical/data-platform-workflows/.github/workflows/release_charm_edge.yaml@v42.1.0
    with:
      track: ${{ needs.tag.outputs.track }}
      artifact-prefix: ${{ needs.ci-tests.outputs.artifact-prefix }}
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
    permissions:
      contents: write # Needed to create git tags
