# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Sync issue to Jira

on:
  issues:
    types: [opened, reopened, closed]

jobs:
  sync:
    name: Sync GitHub issue to Jira
    uses: canonical/data-platform-workflows/.github/workflows/sync_issue_to_jira.yaml@v8
    with:
      jira-base-url: https://warthogs.atlassian.net
      jira-project-key: DPE
      jira-component-names: mongodb-k8s
    secrets:
      jira-api-token: ${{ secrets.JIRA_API_TOKEN }}
      jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
    permissions:
      issues: write  # Needed to create GitHub issue comment
