name: Detect changes on Discourse to raise PR

env:
  BRANCH: main

on:
  workflow_dispatch:
  schedule:
    - cron: '00 16 * * *'

jobs:

  sync-docs:
    name: Raise PR with community contribution on Discourse
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Publish documentation
        uses: canonical/upload-charm-docs@main

        id: publishDocumentation
        with:
          discourse_host: discourse.charmhub.io
          discourse_api_username: ${{ secrets.DISCOURSE_API_USERNAME }}
          discourse_api_key: ${{ secrets.DISCOURSE_API_KEY }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: "true"

      - name: Show migrate output
        run: echo '${{ steps.publishDocumentation.outputs.migrate }}'
      - name: Show reconcile output
        run: echo '${{ steps.publishDocumentation.outputs.reconcile }}'

